md db_linux
copy *.fst db_linux
copy *.pft db_linux
copy *.ctl db_linux
copy uctab db_linux
copy actab db_linux
copy *.bat db_linux
copy *.seq db_linux
crunchmf 001_cal db_linux\001_cal
crunchmf 001_cdu db_linux\001_cdu
crunchmf 001_cxa db_linux\001_cxa
crunchmf 001_emp db_linux\001_emp
crunchmf 001_log db_linux\001_log
crunchmf 001_ser db_linux\001_ser
crunchmf 001_ser_fmt db_linux\001_ser_fmt
crunchmf 001_tbo db_linux\001_tbo
crunchmf 001_tbo_fmt db_linux\001_tbo_fmt
crunchmf 001_usc db_linux\001_usc
crunchmf phl_acv db_linux\phl_acv
crunchmf phl_acv_fmt db_linux\phl_acv_fmt
crunchmf phl_aqu db_linux\phl_aqu
crunchmf phl_ass db_linux\phl_ass
crunchmf phl_aut db_linux\phl_aut
crunchmf phl_cnf db_linux\phl_cnf
crunchmf phl_cnt db_linux\phl_cnt
crunchmf phl_col db_linux\phl_col
crunchmf phl_cpa db_linux\phl_cpa
crunchmf phl_cur db_linux\phl_cur
crunchmf phl_for db_linux\phl_for
crunchmf phl_for_fmt db_linux\phl_for_fmt
crunchmf phl_gen db_linux\phl_gen
crunchmf phl_idm db_linux\phl_idm
crunchmf phl_log db_linux\phl_log
crunchmf phl_mec db_linux\phl_mec
crunchmf phl_nda db_linux\phl_nda
crunchmf phl_pen db_linux\phl_pen
crunchmf phl_per db_linux\phl_per
crunchmf phl_pqt db_linux\phl_pqt
crunchmf phl_prc db_linux\phl_prc
crunchmf phl_pwd db_linux\phl_pwd
crunchmf phl_rel db_linux\phl_rel
crunchmf phl_res db_linux\phl_res
crunchmf phl_rgl db_linux\phl_rgl
crunchmf phl_set db_linux\phl_set
crunchmf phl_spt db_linux\phl_spt
crunchmf phl_tpr db_linux\phl_tpr
crunchmf phl_usr db_linux\phl_usr
crunchmf phl_usr_fmt db_linux\phl_usr
crunchmf phl_voc db_linux\phl_voc

crunchif 001_cal db_linux\001_cal
crunchif 001_cdu db_linux\001_cdu
crunchif 001_cxa db_linux\001_cxa
crunchif 001_emp db_linux\001_emp
crunchif 001_log db_linux\001_log
crunchif 001_ser db_linux\001_ser
crunchif 001_ser_fmt db_linux\001_ser_fmt
crunchif 001_tbo db_linux\001_tbo
crunchif 001_tbo_fmt db_linux\001_tbo_fmt
crunchif 001_usc db_linux\001_usc
crunchif phl_acv db_linux\phl_acv
crunchif phl_acv_fmt db_linux\phl_acv_fmt
crunchif phl_aqu db_linux\phl_aqu
crunchif phl_ass db_linux\phl_ass
crunchif phl_aut db_linux\phl_aut
crunchif phl_cnf db_linux\phl_cnf
crunchif phl_cnt db_linux\phl_cnt
crunchif phl_col db_linux\phl_col
crunchif phl_cpa db_linux\phl_cpa
crunchif phl_cur db_linux\phl_cur
crunchif phl_for db_linux\phl_for
crunchif phl_for_fmt db_linux\phl_for_fmt
crunchif phl_gen db_linux\phl_gen
crunchif phl_idm db_linux\phl_idm
crunchif phl_log db_linux\phl_log
crunchif phl_mec db_linux\phl_mec
crunchif phl_nda db_linux\phl_nda
crunchif phl_pen db_linux\phl_pen
crunchif phl_per db_linux\phl_per
crunchif phl_pqt db_linux\phl_pqt
crunchif phl_prc db_linux\phl_prc
crunchif phl_pwd db_linux\phl_pwd
crunchif phl_rel db_linux\phl_rel
crunchif phl_res db_linux\phl_res
crunchif phl_rgl db_linux\phl_rgl
crunchif phl_set db_linux\phl_set
crunchif phl_spt db_linux\phl_spt
crunchif phl_tpr db_linux\phl_tpr
crunchif phl_usr db_linux\phl_usr
crunchif phl_usr_fmt db_linux\phl_usr
crunchif phl_voc db_linux\phl_voc
